name: Periodic PR Reminders

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send reminders for PRs with "Ready for review"
        run: |
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          
          # Fetch PRs with "Ready for review" label
          PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?labels=Ready%20for%20review&state=open&per_page=100")
          PR_COUNT=$(echo $PRS | jq '. | length')
          
          if [ "$PR_COUNT" -eq 0 ]; then
            echo "No PRs with 'Ready for review' label found."
            exit 0
          fi

          # Iterate over each PR and send a reminder
          for row in $(echo "${PRS}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            PR_TITLE=$(_jq '.title')
            PR_URL=$(_jq '.html_url')
            PR_AUTHOR=$(_jq '.user.login')

            # Send Slack notification
            curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"*Reminder:* Pull Request '${PR_TITLE}' is still in review. Please take action!\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \":warning: *PR Title*: ${PR_TITLE}\"
                  }
                },
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Author*: ${PR_AUTHOR}\"
                  }
                },
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*PR Link*: <${PR_URL}|Click here to review>\"
                  }
                }
              ]
            }" \
            $SLACK_WEBHOOK_URL
          done