name: Periodic PR Reminders

on:
  pull_request:
    types: [labeled]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send reminders for PRs with "Ready for review"
        run: |
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          
          # Fetch PRs with "Ready for review" label
          PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?labels=TestLabel&state=open&per_page=100")
          PR_COUNT=$(echo $PRS | jq '. | length')
          
          if [ "$PR_COUNT" -eq 0 ]; then
            echo "No PRs with 'Ready for review' label found."
            exit 0
          fi

          # Iterate over each PR and send a reminder
          for row in $(echo "${PRS}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            $PR_NUMBER=$(_jq '.number')
            PR_TITLE=$(_jq '.title')
            PR_URL=$(_jq '.html_url')
            PR_AUTHOR=$(_jq '.user.login')

            PR_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${$PR_NUMBER}")
            PR_ADDITIONS=$(echo $PR_DETAILS | jq '.additions')
            PR_DELETIONS=$(echo $PR_DETAILS | jq '.deletions')

            echo "PR #$PR_NUMBER: $PR_TITLE"
            echo "Additions: $PR_ADDITIONS, Deletions: $PR_DELETIONS"
            echo "$PR_DETAILS" | jq .

            
          done