name: Run Tests on PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync
        working-directory: src

      - name: Compile SAL stylesheet
        run: uv run streamlit-sal compile
        working-directory: src

      - name: Run tests
        run: ./run_tests.sh --maxfail=1 --disable-warnings --verbose
